# Generated by Django 4.2.7 on 2024-01-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='newreview',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newreview',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
