# Generated by Django 4.2.7 on 2024-02-14 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0005_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='newreview',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
