# Generated by Django 4.2.7 on 2024-02-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0006_newreview_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newreview',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
